version: "3.9"


services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      bridge:
        aliases:
          - zookeeper


  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
    depends_on:
      - zookeeper
    networks:
      bridge:
        aliases:
          - kafka


  kafka-producer:
    build: 
      context: ./kafka-producer
    container_name: kafka-producer
    environment:
      KAFKA_SERVER: kafka:9092
      ZOOKEEPER_SERVER: zookeeper:32181
      PRODUCER_INTERVAL: 100
    depends_on:
      - zookeeper
      - kafka
      - kafka-consumer
    networks:
      - bridge


  kafka-consumer:
    build: 
      context: ./kafka-consumer
    container_name: kafka-consumer
    environment:
      KAFKA_SERVER: kafka:9092
      ZOOKEEPER_SERVER: zookeeper:32181
      PRODUCER_INTERVAL: 100
    depends_on:
      - kafka
      - postgres
    networks:
      - bridge


  postgres:
    build: 
      context: ./postgres
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 5432:5432
    networks:
      - bridge
      

volumes:
  settings:
  data:

networks:
  bridge:
    driver: bridge