version: '3.9'



services:

  spark-master:
    build:
      context: ./docker-images/spark
      dockerfile: Dockerfile
    image: spark-master:latest
    container_name: spark-master
    hostname: spark_master
    volumes:
      - ./data:/opt/spark-data
    environment:
      - SPARK_MODE=master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    expose:
      - "7077"
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - de_network


  spark-worker:
    image: docker.io/bitnami/spark:3.4.3
    depends_on: 
      - spark-master
    deploy: 
      replicas: 3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/opt/spark-data
    networks:
      - de_network


networks:
  de_network:
    driver: bridge
    name: de_network